### ISSUE TITLE
Can not install the dtb firmware in ubuntu 12.04

### ISSUE THREAD

**Issue by jsiado** [psi46/pixel-dtb-firmware#7]
We were trying to run pxar code in ubuntu 12.04 64 bits, when updating the firmware we ran into this error message

[16:25:12.676]     INFO:       reading data/N00602//trimParameters_C14.dat
[16:25:12.681]     INFO:       reading data/N00602//trimParameters_C15.dat
[16:25:12.685]     INFO:       reading data/N00602//tbParameters.dat
[16:25:12.685]     INFO:         clk: 4
[16:25:12.685]     INFO:         ctr: 4
[16:25:12.685]     INFO:         sda: 19
[16:25:12.685]     INFO:         tin: 9
[16:25:12.685]     INFO:         level: 15
[16:25:12.685]     INFO:         triggerdelay: 0
[16:25:12.685]    QUIET: Instanciating API for pxar v1.8.0+67~gdea5405
[16:25:12.685]     INFO: Log level: INFO
[16:25:13.254] CRITICAL: <USBInterface.libftdi.cc/EnumNext:L211>  USBInterface::EnumNext(): Error polling USB device number 0
pxar caught an internal exception:  USBInterface::EnumNext(): Error polling USB device​

Does anyone knows how to solve this issue? 

We were able to update the firmware an run pxar in a MAC computer.

**Comment by simonspa** [comment]
This most likely is an issue of access rights to your computer's USB devices and neither a pxar nor a firmware issue. Are you sure you have the rights to access attached USB devices?

**Comment by cfangmeier** [comment]
Hi Simon,

Well, We tried `chmod 777 ` on the appropriate device nodes and this didn't fix the problem. Are there more fine-grained access permissions that need to be set? I guess we didn't try just running it with `sudo`(We weren't quite that desperate yet :) )

For what it's worth, this was tried using firmware 4.0(as well as 3.6 I think) and the latest pXar. 

I agree it's probably not really an issue with pXar/firmware per-se, If there is a more appropriate forum to find help with this, let us know. :)

**Comment by simonspa** [comment]
Hi @cfangmeier,

I have literally no experience with OS X so I guess I'm not really of any help here, I'm sorry. Under Linux I usually recommend using udev to set proper permissions, but `644` are totally sufficient.

**Comment by cfangmeier** [comment]
Ah, Well, to be clear. We have both OSX and Ubuntu machines that we need pXar on. This problem is on the Ubuntu machine. I guess the udev rule we need is 

`SUBSYSTEM=="usb", ATTR{idVendor}=="0403", ATTR{idProduct}=="6014", ATTR{manufacturer}=="PSI", GROUP="plugdev", MODE="0664"` 

(from TWiki)
perhaps with the group name adjusted.

**Comment by simonspa** [comment]
Hi Caleb,

Sorry, I completely misunderstood the OS business above... :)

Yes, these udev rules should be fine and the executing user should be in the plugdev user group. I think this is the case by default under Ubuntu.

/Simon

**Comment by simonspa** [comment]
Any luck with udev?

**Comment by jsiado** [comment]
Hi Simonspa, Caleb helped me with the udev rule and we were able to install a run pxar in our ubuntu machine. 

thanks
